name: Publish to hc224.dev Repository Release
# Publish manually
on:
  workflow_dispatch:
  release:
    types: [ published ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Create gradle properties file
        env:
          MAVEN_NAME: ${{ secrets.MAVEN_NAME }} # token
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }} # password
        shell: bash
        run: |
          mkdir -p ~/.gradle/
          echo "HC224ReleasesUsername=$MAVEN_NAME" >> ~/.gradle/gradle.properties
          echo "HC224ReleasesPassword=$MAVEN_TOKEN" >> ~/.gradle/gradle.properties
      - name: Publish with Gradle
        run: ./gradlew build publish

